version: "3"
services:
  hapi-fhir-jpaserver-start:
    #build: .
    image: hapiproject/hapi:v7.4.0
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      # this parameter was missing from master branch
      # unless this is set, service will log a lot of "table not found errors"
      spring.jpa.properties.hibernate.dialect: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
      # lets work with the R5 release
      hapi.fhir.fhir_version: R5
      # all the resources load to happen in arbitrary order
      hapi.fhir.enforce_referential_integrity_on_write: false 
      # enable bulk IO
      hapi.fhir.bulk_export_enabled: true 
      hapi.fhir.bulk_import_enabled: true
    ports:
      - "8080:8080"
  hapi-fhir-postgres:
    image: postgres:15-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
volumes:
  hapi-fhir-postgres:
